### ISSUE TITLE
About "Web page content Centering" issues

### ISSUE THREAD

**Issue by ccjoe2020** [jiruochong/jiruochong.github.io#1]
Hi, ruochong

You can add  div tag and styles to set content center.

body
div style="max-width:1200px;position:absolute;left:0;right:0;margin:0 auto;"
....your content.....
div
body

Best regards

**Comment by jiruochong** [comment]
Thank you for your suggestion, which I have corrected.

**Comment by jiruochong** [comment]
Hi, xiaofeng

Thank you for your suggestion, which I have corrected.

Best regards

**Comment by ccjoe2020** [comment]
Yes, the web page looks good now.
