### ISSUE TITLE
About share  youtube video

### ISSUE THREAD

**Issue by ccjoe2020** [jiruochong/jiruochong.github.io#2]
Hi， Ruochong

You can add video to body end and share your youtube video.

Please reference ”https://support.google.com/youtube/answer/171780?hl=zh-Hans“

`<!--share youtube video start-->`
`<div class="stl_02">`
			`<div class="stl_03">`
				`<iframe width="1200px" height="800px" src="https://www.youtube.com/embed/hiIpT4O_VkM?si=RXc-wCpMgsu-VgdP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>`
                                `</iframe>`
`</div>`
`</div>`
`<!--share youtube video end-->`
`</body>`

Best Regards

**Comment by jiruochong** [comment]
Hey Joe

thank you for the issue. I have changed it, and shared the video in my page.

Best Regards
